name: stock-lstm-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - pandas>=2.0
  - numpy>=1.24
  - scikit-learn>=1.3
  - yfinance>=0.2.40
  - tensorflow>=2.15,<2.16
  - keras>=3.0
  - pip:
      - --upgrade pip
